
<p><a href="<?php echo $this->url(
        array(
            'controller' => 'guestbook',
            'action'     => 'sign'
        ),
        'default',
        true) ?>">Leave a message, please</a></p>

<table border="1"  >

        <caption>Guestbook</caption>
        <tr bgcolor="#c0e4ff">
            <th><p>User Name </th>
            <th><p>Email</th>
            <th><p>Data </th>
            <th><p>Message text</th>
        </tr>

             <?php foreach ($this->entries as $entry): ?>
            <tr><td><?php echo $this->escape($entry->User_name) ?></td>
        <td><?php echo $this->escape($entry->email) ?></td>
        <td><?php echo $this->escape($entry->created) ?></td>
        <td><?php echo $this->escape($entry->comment) ?></td>
        <?php endforeach ?>
            </tr>

</table>

