
<p><a href="<?php echo $this->url(
        array(
            'controller' => 'guestbook',
            'action'     => 'sign'
        ),
        'default',
        true) ?>">Leave a message, please</a></p>
Guestbook Entries: <br />
<dl>
        <?php foreach ($this->entries as $entry): ?>
            <dt><?php echo $this->escape($entry->email) ?></dt>
            <dt><?php echo $this->escape($entry->created) ?><dt>
            <dd><?php echo $this->escape($entry->comment) ?></dd>
            <?php endforeach ?>
</dl>